baseURL = 'https://github.com/AT-Blaze/AT-Blaze.github.io.git/'
languageCode = 'en-us'
title = 'Blaze Blogs'
theme = 'PaperMod'

#[[menu.main]]
#identifier = "categories"
#name = "Categories" #this one is what shows in the header
#url = "/categories/"
#weight = 10

#[[menu.main]]
#identifier = "tags"
#name = "tags"
#url = "/tags/"
#weight = 20


