baseURL: 'https://github.com/AT-Blaze/AT-Blaze.github.io.git/'
canonifyURLs: true #this allows for the rendering of my images in the local server (idky it doesnt work any other way, relativeURLs destroys my CSS, and changing baseURL didnt help
languageCode: 'en-us'
title: 'Blaze Blogs'
theme: 'PaperMod'

taxonomies:
    tag: tags
    series: series
menu:
    main: 
        - name: About
          url: about
          weight: 10
        - name: Categories 
          url: tags
          weight: 10 
#        - name: Academics
#          url: academics #points to the academics folder in content/
#          weight: 10
        - name: Parker Chirps
          url: parker-test
params:
    homeInfoParams:
        Title: BlazeBlogs is getting a makeover...
        Content: I don't think I want to keep this site up the way it currenlty is. I thought about entirley taking it down, after all no one really reads it, and I'm not sure I *need* to have a PUBLIC permanent record that speaks direclty to the future. I also don't feel like maintaining it, and also filtering what I want to say. But I suppose on the off chance that I ever say something worth saying again, ill leave the site up for that, but im changing whats public right now.

    socialIcons: # optional
#        - name: "github"
#          url: 
#        - name: "instagram"
#          url: 
#        - name: "linkedin"
#          url: 

markup:
  goldmark:
    extensions:
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: simple
        enable: false
        escapedSpace: false
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false


#params:
#    profileMode:
#        enabled: true
#        title: "Welcome to my blog!" # optional default will be site title
#        subtitle: "prepare your mind"
#        #imageUrl: "<image link>" # optional
#        #imageTitle: "<title of image as alt>" # optional
#        imageWidth: 120 # custom size
#        imageHeight: 120 # custom size
#        buttons:
#            - name: Find my blogs here
#              url: "posts"
#            #- name: Github
#              #url: "https://github.com/"
#
#    socialIcons: # optional
#        - name: "<platform>"
#          url: "<link>"
#        - name: "<platform 2>"
#          url: "<link2>"
