baseURL: 'https://github.com/AT-Blaze/AT-Blaze.github.io.git/'
canonifyURLs: true #this allows for the rendering of my images in the local server (idky it doesnt work any other way, relativeURLs destroys my CSS, and changing baseURL didnt help
languageCode: 'en-us'
title: 'Blaze Blogs'
theme: 'PaperMod'

taxonomies:
    tag: tags
    series: series
menu:
    main: 
        - name: About
          url: about
          weight: 10
        - name: Categories 
          url: tags
          weight: 10 
        - name: Academics
          url: academics #points to the academics folder in content/
          weight: 10
        - name: Christmas List?
          url: xmas-list
params:
    homeInfoParams:
        Title: Hi! Welcome to my blog...
        Content: This is a place where I put all my silly little thoughts about things that I think about. You can read them below. Below is a chronological list of the posts I've written, some are text based and some are audio. If you want to fiter by type you can view the "Categories" page in the top right corner. Or you can find out more about me at the "About" page. You can also check out my socials below.

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/AT-Blaze"
        - name: "instagram"
          url: "https://www.instagram.com/boulder.blaze/"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/antranig-douglas"

#params:
#    profileMode:
#        enabled: true
#        title: "Welcome to my blog!" # optional default will be site title
#        subtitle: "prepare your mind"
#        #imageUrl: "<image link>" # optional
#        #imageTitle: "<title of image as alt>" # optional
#        imageWidth: 120 # custom size
#        imageHeight: 120 # custom size
#        buttons:
#            - name: Find my blogs here
#              url: "posts"
#            #- name: Github
#              #url: "https://github.com/"
#
#    socialIcons: # optional
#        - name: "<platform>"
#          url: "<link>"
#        - name: "<platform 2>"
#          url: "<link2>"
